language: rust
cache: cargo

os:
  - linux
  - osx
  - windows
script:
  - cargo test --lib --locked
  - rustup component add rustfmt-preview
  - cargo fmt --all -- --check
  - cargo build --release
before_deploy:
  - git config --local user.name "Peter Smith"
  - git config --local user.email "peter@orukusaki.co.uk"
  - name="hex2wav-$TRAVIS_TAG-$TARGET"
  - mkdir $name
  - cp target/$TARGET/release/hex2wav $name/
  - cp README.md LICENSE $name/
  - tar czvf $name.tar.gz $name
deploy:
  provider: releases
  api_key:
    secure: "jq1LycKjHKCeODgqVPMnlYp38JTIvmYzFovwdm5Rox+3BEoQ6fSfRzheEXy5BjSa9AH6wr5i+SDl6J8rvHeGyEbv8QI+T8++ShrKQipsEU3fFVubeLoAixVXKzl1NgCGzijHRC21GFqFheggbih6iuFMNi9AgVi6UZ22L4DPHBjclBgJ9oTz5Vk1XSh38keJTIv0WHSYeUfopVmwCHGwKfLYNsgRdAg5Dw0DOEal+WJdlNAmds62Yy3pjJroHTdycot5bnxzPe37MCBGrX7PVEJ0PyQF586Nbl6GAuJ6DEy6fMKOdzrFThO/YvVxih8VxFo9s1sbx/GSqmhBStWeC5o5cCEcFLQXwkQvV3Sn0bab6MT9zEfBQwc+i2g6hQeIQrfJ1dmmaRjdrB8Z1TRZ6oKiBH5WwviXxQKalm+Tv2PRPfN8+eq0iP7G978p0KDg202D2gC03kdyXY3plbxBz19VJPgNxifiR+b+zwGVmgDUf2NwfmZHYy+hKrwINvTiVLa7svjbyQHR5TC68i6hjwUnBsf7e9TLMg5J5nV0gvDrazIyccHo+SwIscSHatE0N2JamXix9cSmfmpKazkaYkd61ztZ+xmlK2Y0EOAcfzH6gzbqk5JZx6WJrPNywhWT7B7MqfHnidIuT6ydcOGK8JSHi46bsLCbFoTRAJ5PHb4="
  file: hex2wav-$TRAVIS_TAG-$TARGET.tar.gz
  skip_cleanup: true
  on:
    branch: main
    tags: true
